# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'movie_location',
            },
        ),
    ]
