# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocomplete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
